# Generated by Django 5.0.1 on 2024-02-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deudores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('fecha', models.DateTimeField()),
                ('deuda_inicial_pesos', models.FloatField()),
                ('deuda_inicial_dolares', models.FloatField()),
                ('deuda_actualizada_pesos', models.FloatField()),
            ],
        ),
    ]
