# Generated by Django 5.0.1 on 2024-02-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deudores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deudores',
            name='deuda_actualizada_pesos',
        ),
        migrations.AlterField(
            model_name='deudores',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
