# Generated by Django 5.0.1 on 2024-02-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deudores', '0002_remove_deudores_deuda_actualizada_pesos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deudores',
            name='intereses_mensuales',
            field=models.IntegerField(default=0),
        ),
    ]
